server:
  port: 9088

openai:
  key: xx
  baseUrl: https://api.openai.com/
  useProxy: true
  proxyUrl: 127.0.0.1
  proxyPort: 7890

cloud:
  mongodb:
    url: xx
    dbName: chat

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.security: DEBUG

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
