server:
  port: 9088

openai:
  key: xx
  baseUrl: https://api.openai.com/
  useProxy: true
  proxyUrl: 127.0.0.1
  proxyPort: 7890

cloud:
  mongodb:
    url: xx
    dbName: xx

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
